### ISSUE TITLE
Create script to populate DB from Google Sheet

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#120]
_this depends on #45_

While we work on creating a better UI for updating resource information, we'll be using a Google Form that will populate info into a Google Sheet.

A script will need generated to take the information in that sheet and transfer it to our [local DB](https://github.com/CodeForBoulder/upswyng/blob/master/data_pipeline/charity.json).

## Tech Notes

- In the form, we do not request the latitude or longitude of physical location of the resource. This will need to be generated via the address provided in the form.
- Some inputs requested in the form are not part of our current DB model. We'll need to some up with a schema for these additional items .

_More notes to come._

**Comment by rhinodavid** [comment]
We got dat server now
