### ISSUE TITLE
Update Node Version

### ISSUE THREAD

**Issue by jollyjerr** [CodeForBoulder/upswyng#166]
Currently, the workspace only runs on Node ~> 11.10

### Main Error
```error workspace-aggregator-9e4008a1-9a4a-40d4-9a75-7e9c1888c803@0.1.0: The engine "node" is incompatible with this module. Expected version ">=10.17.0 <12.0.0```

>Switching too low (~>10.17.0) results in a similar error.

This issue is most likely due to something leftover from Firebase and/or React Native

**Comment by jacobvenable** [comment]
While we do currently enforce a node version, I believe this is intentional to match our production environment. @rhinodavid can you confirm?

**Comment by jollyjerr** [comment]
## Totes
