### ISSUE TITLE
[web] Fetch Categories/Subcategories from the server

### ISSUE THREAD

**Issue by rhinodavid** [CodeForBoulder/upswyng#184]
[Currently, categories and subcategories are hardcoded into the web client](https://github.com/CodeForBoulder/upswyng/blob/master/packages/upswyng-web/src/components/Categories.tsx#L37). We should make these be fetched dynamically from the server. The endpoints are already in place (I think). This will allow us flexibility, particularly if we expand to areas and want locales to be able to customize their categorization.

**Comment by jacobvenable** [comment]
Does this endpoint also include icons used on the home page?

Could you add more info about the endpoint that would be used?

**Comment by rhinodavid** [comment]
duplicate of #342
