### ISSUE TITLE
[server] Document API Endpoints

### ISSUE THREAD

**Issue by rhinodavid** [CodeForBoulder/upswyng#257]
Some of the API endpoints (`packages/upswyng-server/src/routes/api/**`) have comments explaining what the endpoint does, what the request should look like, and what a successful and error response look like, but some don't.

We should select a standard way of documenting these ([maybe APIDoc?](https://apidocjs.com/)) and complete documentation. We could also add a script to generate an API manual from the docs.

**Comment by amites** [comment]
How's openAPI sound?

you start with yaml or json (yaml often easier to edit by humans)
https://swagger.io/specification/

and get outputs like
https://petstore.swagger.io/v2/swagger.yaml

**Comment by amites** [comment]
Started on a yaml openapi doc -- documents the GET categories endpoint so far

likely to put on hold until I hear input that this is a good direction

https://github.com/CodeForBoulder/upswyng/pull/481/files

**Comment by amites** [comment]
PR ready to review -- let me know if there should be more than the `/api` endpoints

ie: /provider

to login and others
