### ISSUE TITLE
[Landing Page] As a person experiencing homelessness, I need to land on a main page so that I can orient myself in the application.

### ISSUE THREAD

**Issue by amaliebarras** [CodeForBoulder/upswyng#26]
![home.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/565201200fec5f3e00d1ff86/125516c66e82c728ace21e0d46e09b9726c0cfeb9ffbb049a15ee4d6730472707e57f37373d5ba2eeb407a515f5e4bfa415c0a44fcfc9b37b4f46d2ede0356b49b381d66cc2f10abb2831aba00bf248e4880b3bd8a4dd2a5.png)

- menu should say 'menu'
- logo should be ever present inline with the menu 
- search should be prominent on the main page
- coordinated entry button must stay
- more important content (food, shelter) should be more prominent than less important (education, pets)
- Icons could be laid out in blocks instead of circles in order to use space better

**Comment by rhinodavid** [comment]
![Home – 52](https://user-images.githubusercontent.com/5778036/58599778-f3b7c100-823e-11e9-9d6b-85e85ad11b85.jpg)
![Home – 51](https://user-images.githubusercontent.com/5778036/58599780-f3b7c100-823e-11e9-8dd2-74e089904d65.jpg)
