### ISSUE TITLE
update provider portal landing page content

### ISSUE THREAD

**Issue by aliza614** [CodeForBoulder/upswyng#288]
Content on the [provider landing page](https://github.com/CodeForBoulder/upswyng/blob/master/packages/upswyng-server/src/routes/index.svelte) needs the following updates:

- [ ] a search bar that submits to the search found in the provider portal
   - _Note: this is different than the search page found in the `upswyng-web` package_
- [ ] a heading level one containing "Upswyng Provider Portal" as the content
- [ ] two additional paragraphs added to containing this content:
   - Welcome to the Provider’s Portal. This is the place to update your organization’s information so it’s the latest and most accurate for the at-risk community. 
   - We have made an easy and intuitive portal for you to make changes. All changes are subject to confirmation before going live. Just update and save as a draft and we will do the rest.

**Comment by jacobvenable** [comment]
Unfortunately we don't have designs for this. You would have some creative freedom with how it's implemented, but design review would still be part of the PR.
