### ISSUE TITLE
[Listing Page] As a person experiencing homelessness, when I hear about a service I need to know some basic information so that I can determine if using the resource is feasible for me.

### ISSUE THREAD

**Issue by amaliebarras** [CodeForBoulder/upswyng#29]
![listing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/565201200fec5f3e00d1ff86/125516c66e82c728ace21e0d46e49d89378b8daecda5fd53b652fa912a5265296b51a07c23d5bb2bef1b7d550d0e4eac405d0944f8ac892ba3a42062c80d55b98e30063e937f03a6aa8317b500bf258a4a81b0bb8d44c9ed3a37aa.png)

## Info Displayed on a Listing Page
- existing information:
   - [ ] Resource Name
   - [ ] Address
   - [ ] who it is for
   - [ ] what they offer
   - [ ] Full description
   - [ ] website
   - [ ] phone number
   - [ ] whether they are open or closed
   - [ ] whether user has favorited it or not
   - [ ] hours of operation
- missing information
   - [ ] image of the resource (optional)
- sub-components to be built
   - [ ] carousel for multiple images
   - [ ] map embed with #40

**Comment by jacobvenable** [comment]
Since this is an individual listing, should the category bar still be located on the page? @amaliebarras

**Comment by amaliebarras** [comment]
You're right, that's a little weird. I think that could go away. Optionally, we could add navigation back to the listings, but also I think users would likely just use the back button on their browser to get back.

**Comment by jacobvenable** [comment]
Closing in favor of the smaller issues left with this page.
