### ISSUE TITLE
implement ability for users to add favorite services

### ISSUE THREAD

**Issue by amaliebarras** [CodeForBoulder/upswyng#33]
We want to enable users to add listings to a favorites list for easy future access.

## Technical Considerations

- we don't provide any type of user-login, so favorites will need to be stored via local storage
- an endpoint will need created that accepts a list of resource IDs 

### Add to Favorites

On an [individual listing](http://beta.upswyng.org/resource/5def5cb7b831a048f2a3deed), display a [floating action button](https://material-ui.com/components/floating-action-button/#floating-action-button) that adds/removes an item from the user's favorites.

- [ ] when favorited, display a [primary orange](https://github.com/CodeForBoulder/upswyng/blob/master/packages/common/src/colors.ts#L13) favorite icon `import FavoriteIcon from '@material-ui/icons/Favorite';`
- [ ] when not favorited, display a [primary orange](https://github.com/CodeForBoulder/upswyng/blob/master/packages/common/src/colors.ts#L13) favorite border icon `import FavoriteBorderIcon from '@material-ui/icons/FavoriteBorder';`
- [ ] when pressing the button, it toggles whether the resource is favorited or unfavorited
- [ ] when the user has favorited an item for the first time, display an info [snackbar](https://material-ui.com/components/snackbars/#snackbar) that displays the following message for five seconds "Favorites are only saved to this device."

### Favorites Page

- [ ] create a new API endpoint that accepts a list of resource IDs and returns the info needed to display favorites in a view similar to a [category/subcategory list](http://beta.upswyng.org/food)
- [ ] create a favorites page of a similar design to a [category/subcategory list](http://beta.upswyng.org/food)
   - no filtering of resources beyond favorites is needed
   - use the [primary orange](https://github.com/CodeForBoulder/upswyng/blob/master/packages/common/src/colors.ts#L13) color for the banner which contains the text "Favorites"
   - [ ] below the banner but above the favorites list, display an [info alert](https://material-ui.com/components/alert/#alert) with the following text: "Favorites are only saved to this device. They will not be saved if you are using a public computer, or when you have a private session enabled in your browser (incognito mode)."
   - [ ] when no items are favorited, display the following text instead of the favorites list: "You haven't added any favorites yet!"

### Main Menu Link

- [ ] add a "Favorites" link to the favorites page in the main menu using the favorite icon `import FavoriteIcon from '@material-ui/icons/Favorite';`

**Comment by jacobvenable** [comment]
Switching this back to on hold until we can provide more info.
