### ISSUE TITLE
Check **all** rendered content for proper casing of "UpSwyng"

### ISSUE THREAD

**Issue by rhinodavid** [CodeForBoulder/upswyng#351]
Before launch we need a once-over of anything a user might see to make sure the capitalization of the product is consistent and correct. _Note that I'm **not** talking about variable names or any other internal code. Just site copy_

Tasks:
- [ ]  all visual instances of "Upswyng" are changed to "UpSwyng"

**Comment by jacobvenable** [comment]
Completed with #386 🎉
