### ISSUE TITLE
[Provider Flow] As a provider, I need to create and edit a profile for my organization, so that I can publish information to Upswyng and offer help to people experiencing homelessness.

### ISSUE THREAD

**Issue by amaliebarras** [CodeForBoulder/upswyng#36]
![providerflow.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/565201200fec5f3e00d1ff86/125516c66e82c728ace21e0d46f88695358b87ac9defb34cb31fbcd6395428792c07b7692ac7b62be8112b590c5f47fa450a0e44fcf88c7da6b269708a5919f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b98b49c5ea3d26ef828f462c53.png)

- There should be a provider login within the main menu
- The login should take the provider to all listings that they manage
- The provider should be able to create listings
- The provider should be able to edit listings
- The provider should be able to delete listings
- The information should convey that the edits go through approval and take some time to propogate.
- A forgot password flow needs to be considered down the road.

**Comment by jacobvenable** [comment]
For the initial release, this process will revolve around a more manual process. While providers will be able to submit updates/new listings, we'll require a member of the immediate team to audit and update the information. This will be updated later to more of a process described above.

**Comment by jacobvenable** [comment]
@rhinodavid has pummeled this issue into the ground 🎉
