### ISSUE TITLE
Add owners to service providers

### ISSUE THREAD

**Issue by rhinodavid** [CodeForBoulder/upswyng#408]
Create a User ↔️ Resource relationship.

### Questions
- Who can create these relationships?
- Do we need some way to do drafts and then approve them

### Punch List
1. Modify types/schema with new edge
1. Add Model utility to add/remove edge
1. Add api endpoints
1. Create UI

**Comment by jollyjerr** [comment]
Closing this because Jacob and I are breaking this into multiple issues 🤷‍♂️
