### ISSUE TITLE
setup foundation for multi-language support

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#420]
We will eventually be providing multi-language support within the web project once English to Spanish translations can be procured.

In the meantime, development can implement the foundation for that support by creating the setup with English-only.

For this setup, lets use [react-i18 Next](https://react.i18next.com/), which provides some useful [setup instructions](https://react.i18next.com/latest/using-with-hooks).

The application will render as before; however it will enable us to provide other language translations in the future.

**Comment by galbwe** [comment]
@jacobvenable can I grab this issue?

**Comment by jacobvenable** [comment]
Aww ya!! I put it into in progress and assigned!
