### ISSUE TITLE
add labels to inputs in provider portal

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#421]
For our MVP release, there are some inputs when editing a service that aren't easily handled by the Service Providers managing their resource.

Until we can improve them, the following inputs should have help label added beneath them:

- Street View Image URL
   - label text: "(We'll add this for you.)"
- latitude
   - label text: "(We'll add this for you.)"
- longitude
   - label text: "(We'll add this for you.)"

Bulma's [help text](https://bulma.io/documentation/form/general/#form-field) can be used for the label styling.

**Comment by asharonbaltazar** [comment]
Hello, where can I find this issue?
