### ISSUE TITLE
move localized text to common package

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#443]
In #427, some basic localization was setup in the web package as a starting point for adding multi-language support.

There was one noted with placing the translated text into a separate `.json` file, which is the desired end goal.

For this issue, we'll seek to:

- [ ] place english translations in `packages/common/src/i18n/en.json`
- [ ] place spanish translations in `packages/common/src/i18n/es.json`
- [ ] replace [current translations](https://github.com/CodeForBoulder/upswyng/blob/master/packages/web/src/i18n.ts#L7) with those imported from the common package

The intended use of these is just for the `web` package for now. While not needed for this ticket, it would be good to start considering how this could be used by the `server` package too.

**Comment by paspheeris** [comment]
I'm going to start on this issue now!
