### ISSUE TITLE
localize the 404 page

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#445]
In #444 , the translations for the home page were moved to our shared package. We're now ready to enable localization to the rest of the web package.

## Translations
https://docs.google.com/document/d/159Lje8l2kHIXIFcLZ0wQJKW2YrYO8mihw3dS4RdoijI/edit?usp=sharing

## Content
https://github.com/CodeForBoulder/upswyng/blob/master/packages/web/src/components/NotFound.tsx

## Checklist
- [ ] translations for both English and Spanish were added to the [shared package](https://github.com/CodeForBoulder/upswyng/tree/master/packages/common/src/i18n)
- [ ] translation keys were substituted for the correct content

**Comment by paspheeris** [comment]
:white_check_mark: 2464ca8c2936e6465a5dc6268a2e77258af7bb6d
