### ISSUE TITLE
localize hotlines page

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#446]
In #444 , the translations for the home page were moved to our shared package. We're now ready to enable localization to the rest of the web package.

## Translations

https://docs.google.com/document/d/1UFpzMhhCW-8Xbmmo313edBeoOsHTp7PEmQj1noBnNCQ/edit?usp=sharing

## Content

https://github.com/CodeForBoulder/upswyng/blob/master/packages/web/src/components/Hotlines.tsx

## Checklist
- [ ] translations for both English and Spanish were added to the [shared package](https://github.com/CodeForBoulder/upswyng/tree/master/packages/common/src/i18n)
- [ ] translation keys were substituted for the correct content

**Comment by paspheeris** [comment]
:white_check_mark: 7fc026b20ef165d8b03136aac5648aff14896d36
