### ISSUE TITLE
localize search input

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#451]
In #444 , the translations for the home page were moved to our shared package. We're now ready to enable localization to the rest of the web package.

## Translations

"Search Element" section of this document:
https://docs.google.com/document/d/1YzJdUW2tTtJxt5OsTQ5BNjwBUm-Sy2SYGYCUeT3SQB4/edit?usp=sharing

## Content

https://github.com/CodeForBoulder/upswyng/blob/master/packages/web/src/components/SearchInput.tsx

## Checklist
- [ ] translations for both English and Spanish were added to the [shared package](https://github.com/CodeForBoulder/upswyng/tree/master/packages/common/src/i18n)
- [ ] translation keys were substituted for the correct content

**Comment by paspheeris** [comment]
I accidentally took care of this in a [previous PR](https://github.com/CodeForBoulder/upswyng/pull/454/files#diff-67d20f2e1fb3f4e6daab17bce5455373314e1f62df9ed677c54ea378b5406c17R28).

Didn't realize there was a separate issue for it!

**Comment by jacobvenable** [comment]
Ah right thanks for following up!
