### ISSUE TITLE
localize privacy policy

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#461]
In #459 , the translations for the about page markdown were added to the common package. We're now ready to enable localization for our privacy policy.

## Translations

https://docs.google.com/document/d/1DdlQjrvZSGV82M5u7ab3pPlKOlmzl-6Tf4msMUSB0Ow/edit?usp=sharing

## Content

https://github.com/CodeForBoulder/upswyng/blob/master/packages/common/src/content/PrivacyPolicy.md

## Checklist
- [ ] translations for both English and Spanish were added to the shared package
- [ ] translation keys were substituted for the correct web package content
- [ ] the server package was updated to import and use the english version of this content

**Comment by kellydinneen** [comment]
Hi @jacobvenable. I'd love to try this out as a first issue!
