### ISSUE TITLE
localize various accessibility text

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#468]
In #444 , the translations for the home page were moved to our shared package. We're now ready to enable localization to the rest of the web package.

## Translations

https://docs.google.com/document/d/12JxxvJcIySxBMensv48UrhiG0fkaLcCLiUttuuhv8Uk/edit?usp=sharing

## Content

- "[Current Temperature](https://github.com/CodeForBoulder/upswyng/blob/cf0e6bea6bdd2c02278c30ea9f952fd1143c3a5e/packages/web/src/components/Temperature.tsx#L44)"
- "[go back to previous page](https://github.com/CodeForBoulder/upswyng/blob/cf0e6bea6bdd2c02278c30ea9f952fd1143c3a5e/packages/web/src/components/BackButton.tsx#L21)"
- "[menu](https://github.com/CodeForBoulder/upswyng/blob/cf0e6bea6bdd2c02278c30ea9f952fd1143c3a5e/packages/web/src/components/Header.tsx#L26)"
- "[close alerts](https://github.com/CodeForBoulder/upswyng/blob/cf0e6bea6bdd2c02278c30ea9f952fd1143c3a5e/packages/web/src/components/AlertsDrawer.tsx#L53)"

## Checklist
- [x] translations for both English and Spanish were added to the [shared package](https://github.com/CodeForBoulder/upswyng/tree/master/packages/common/src/i18n)
- [x] translation keys were substituted for the correct content

**Comment by cjlynch278** [comment]
Hey Jacob, I'm going to take this and hopefully have a PR submitted this week.

**Comment by jacobvenable** [comment]
Awesome thanks @cjlynch278 !
