### ISSUE TITLE
add Safehouse Progressive Alliance for Nonviolence hotline

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#475]
We discovered that the Safehouse Progressive Alliance for Nonviolence (SPAN), has a 24 hour hotline that we should add to our list of hotlines.

## Tech Notes

- [English content](https://github.com/CodeForBoulder/upswyng/blob/master/packages/common/src/i18n/en.ts#L48)
- [Spanish content](https://github.com/CodeForBoulder/upswyng/blob/master/packages/common/src/i18n/es.ts#L48)
- [list of hotlines](https://github.com/CodeForBoulder/upswyng/blob/master/packages/web/src/components/Hotlines.tsx#L10)

#### Phone

303-444-2424

#### Name

Safehouse Progressive Alliance for Nonviolence Hotline

#### Description

If you, your children or someone else you know is seeking support for abuse, violence or other forms of oppression and discrimination, SPAN is here to help. From abusive relationships, domestic violence, interpersonal violence and elder abuse to oppression and discrimination based on sexual orientation, gender identity, ethnicity, race, religion, age, ability or income level, SPAN offers the support and resources needed to overcome these challenging circumstances.

#### Name

Safehouse Progressive Alliance for Nonviolence Hotline

#### Description

Si usted, sus hijos o alguien más que conozca está buscando apoyo para el abuso, la violencia u otras formas de opresión y discriminación, SPAN está aquí para ayudarlo. Desde las relaciones abusivas, la violencia doméstica, la violencia interpersonal y el abuso de ancianos hasta la opresión y la discriminación basadas en la orientación sexual, la identidad de género, el origen étnico, la raza, la religión, la edad, la capacidad o el nivel de ingresos, SPAN ofrece el apoyo y los recursos necesarios para superar estas circunstancias difíciles.

**Comment by jacobvenable** [comment]
Not ready until we get Spanish translations.

**Comment by roadpilot** [comment]
Can we use Google translate? :: Si usted, sus hijos o alguien que conoce está buscando apoyo por abuso, violencia u otras formas de opresión y discriminación, SPAN está aquí para ayudarlo. Desde relaciones abusivas, violencia doméstica, violencia interpersonal y abuso de ancianos hasta opresión y discriminación por orientación sexual, identidad de género, etnia, raza, religión, edad, capacidad o nivel de ingresos, SPAN ofrece el apoyo y los recursos necesarios para superarlos. circunstancias desafiantes.

**Comment by jacobvenable** [comment]
> Can we use Google translate?

We try to avoid it when we can since it can be clunky without understanding context. I've put a request in the Code for America Slack for a translation. If we can get one, then I'll update the issue. Otherwise, I'm good using Google Translate as a last-resort 👍

**Comment by roadpilot** [comment]
> We try to avoid it when we can since it can be clunky without understanding context.
I'm not sure if this would accelerate the process but what about taking the English->Spanish translation result and plugging it back in as Spanish->English to see if the translation/context was accurate?  If that would eliminate or even reduce the need for a "dependency" translation, it *could* move things along faster.  You know how it goes with dependencies.  : )  Just a thought.

**Comment by jacobvenable** [comment]
> I'm not sure if this would accelerate the process but what about taking the English->Spanish translation result and plugging it back in as Spanish->English to see if the translation/context was accurate? If that would eliminate or even reduce the need for a "dependency" translation, it _could_ move things along faster. You know how it goes with dependencies. : ) Just a thought.

Apologies for missing this, but ya it couldn't hurt if we lack better options. I did request for a translation through the Code for America #2021-gyr-vol-translation channel when I last commented. Hopefully we could get a legitimate one there. If we don't get one back within a week, I'm good with using Google Translates, since it seems to mostly translate back without issue.

**Comment by Sunset05** [comment]
I'll take this on!

**Comment by jacobvenable** [comment]
completed in #486
