### ISSUE TITLE
fix home page tile sizes

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#487]
On the [UpSwyng home page], each tile in a row is meant to stretch to fit the entire height of the row. We've noticed in some mobile screens, the "Job Training" tile isn't stretching to fill the entire row.

We'd like to update the styles of these tiles to ensure this stretching occurs.

## Example of Problem

<img width="345" alt="example-tile-not-stretching" src="https://user-images.githubusercontent.com/6598084/131418798-ac9d917d-ebcf-4483-a6e0-1a90673537ce.png">

## The Goal

<img width="360" alt="example-tile-stretching" src="https://user-images.githubusercontent.com/6598084/131418981-b8af5795-75be-49a2-9fda-5bce17c732b4.png">

**Comment by dannyirwin** [comment]
I'll give it a shot!
