### ISSUE TITLE
Fix types for Map Component

### ISSUE THREAD

**Issue by rhinodavid** [CodeForBoulder/upswyng#58]
PR #49 added the map component, but the typing for the file is incomplete (see discussion in PR).

Add type params for the component, then fix the errors that pop up.

**Comment by rhinodavid** [comment]
to start (Maps.tsx:16)
```
class Map extends Component<any, any> {
```
becomes
```
class Map extends Component<Props, State> {
```
`Props` has been defined but doesn't match what's referenced in the component. `State` will need to be defined.

**Comment by jacobvenable** [comment]
The package we're currently using for maps also does not have complete types. I don't think we'll be able to address this without providing types for that package or switching to something else. For the time being I'm going to close and we can address in the future.
