### ISSUE TITLE
[Temperature Feature] As a person in Boulder experiencing homelessness, I'd like to know the current temperature

### ISSUE THREAD

**Issue by rhinodavid** [CodeForBoulder/upswyng#61]
Below, **boxed in red**, is an example of the temperature in the header of the application.

![example of temperature in header](https://user-images.githubusercontent.com/6598084/64746365-8156ae00-d4c8-11e9-9138-760aa649997f.png)

For our data source, we can use [Open Weather](https://openweathermap.org/).

**Comment by rhinodavid** [comment]
![image](https://user-images.githubusercontent.com/5778036/58665823-fa057600-82ee-11e9-8fc3-abf84cd73b59.png)

Right now we'll just limit this to boulder.

**Comment by mhomner** [comment]
https://www.weather.gov/documentation/services-web-api

Mike ;-)
Homner Design
