### ISSUE TITLE
Remove legacy references to data sources once migrated

### ISSUE THREAD

**Issue by rhinodavid** [CodeForBoulder/upswyng#72]
- Remove data dumps in `data_pipeline`
- Remove download scripts in `package.json` (or update them to point at our own data)
- Revert `isolatedModules` change
- Remove types which reference Strapped data
- Rename `...Upswyng...` types to not specify Upswyng, since they're now canonical
- Remove conversion utilities/scripts

**Comment by rhinodavid** [comment]
The `isolatedModules` is in `tsconfig.json` and the change was made in #73

**Comment by jacobvenable** [comment]
@rhinodavid should we wait to close this until "Legacy ID" is removed from resources?

**Comment by rhinodavid** [comment]
We need the legacy ID so re-syncs from strappd can happen. At this point we could probably just remove anything having to do with Strappd, but that should be a different issue.
