### ISSUE TITLE
Move test files to the __tests__ folder

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#81]
We'll be keeping our test files in the [`src/components/__tests__/`](https://github.com/CodeForBoulder/upswyng/tree/master/src/components/__tests__) folder.

Any test files, those ending in `.spec.tsx`, `.spec.ts`, `.spec.jsx`, or `.spec.js` will need to be moved there.

**Comment by MartinRosenberg** [comment]
I would like to take this ticket.
