### ISSUE TITLE
Update Instances of "Soup Kitchen" to "Meal"

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#88]
Within our admin interface, we'll want to ensure that any listed resources that use the word "soup kitchen" are updated to use "meal" or "meals" instead.

**Comment by MartinRosenberg** [comment]
I'd like to make sure I'm reading this correctly:

If "soup kitchen" is in the service name, leave "soup kitchen" in the other properties.
Else if "soup kitchen" is in the other properties, replace it with "meal".
Else don't change anything.

**Comment by jacobvenable** [comment]
@MartinRosenberg apologies for the delay but yes you are reading that correctly!

@rhinodavid does it make sense to add this as a command to your Slack bot? Something that suggests better words? E.g. use "meal" instead of "soup kitchen", use "without shelter" instead of "homeless"?
